#!/bin/sh /etc/rc.common
# Authenticating utility for auth.tsinghua.edu.cn
# This init script is used explicitly with OpenWRT

USE_PROCD=1
START=98
PROG="/usr/bin/goauthing"  # cp script to this path first
CONF="/etc/goauthing.json"

generate_command() {
CMD="\
\"$PROG\" -c \"$CONF\" -D deauth; \
\"$PROG\" -c \"$CONF\" -D auth; \
\"$PROG\" -c \"$CONF\" -D login; \
\"$PROG\" -c \"$CONF\" -D online; \
"
}

start_service() {
	generate_command
	procd_open_instance
	procd_set_param command sh
	procd_append_param command -c "$CMD"
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	"$PROG" -c "$CONF" -D logout
}
